### PR TITLE
Add proxy parameter to bot builder

### PR DESCRIPTION
**Pull request by misemyon**
Add support for connecting to telegram servers through a proxy.

### CODE REVIEW

**Comment by avently** [comment]
@seik can you merge this PR? Or you found some issues with it? For now there is no way to use Telegram without proxy in our country. So proxy support is important

**Comment by seik** [comment]
Hi, never realised how important this feature was. LGTM! Thanks @misemyon 

cc @avently

**Comment by seik** [comment]
Released 0.3.7 with this changes.

https://jitpack.io/#Seik/kotlin-telegram-bot/0.3.7

**Comment by avently** [comment]
Thank you, guys!

**Pull request merged**
